routes/web.php
	Route::post(	'categoryDefinition/ds',	[	'uses' => 'Resources\CategoryDefinitionController@ds',			'as' => 'resource.categoryDefinition.ds'	]);
	Route::resource('categoryDefinition',			'Resources\CategoryDefinitionController',				$resource_actions);

	Route::post(	'cliente/ds',				[	'uses' => 'Resources\ClienteController@ds',						'as' => 'resource.cliente.ds'				]);
	Route::resource('cliente',					'Resources\ClienteController',							$resource_actions);

	Route::post(	'comentario/ds',			[	'uses' => 'Resources\ComentarioController@ds',					'as' => 'resource.comentario.ds'			]);
	Route::resource('comentario',					'Resources\ComentarioController',						$resource_actions);

	Route::post(	'configuracion/ds',			[	'uses' => 'Resources\ConfiguracionController@ds',				'as' => 'resource.configuracion.ds'			]);
	Route::resource('configuracion',				'Resources\ConfiguracionController',					$resource_actions);

	Route::post(	'cotizacion/ds',			[	'uses' => 'Resources\CotizacionController@ds',					'as' => 'resource.cotizacion.ds'			]);
	Route::resource('cotizacion',					'Resources\CotizacionController',						$resource_actions);

	Route::post(	'destino/ds',				[	'uses' => 'Resources\DestinoController@ds', 					'as' => 'resource.destino.ds'				]);
	Route::resource('destino',					'Resources\DestinoController', 						$resource_actions);

	Route::post(	'excepcion/ds',				[	'uses' => 'Resources\ExcepcionController@ds', 					'as' => 'resource.excepcion.ds'				]);
	Route::resource('excepcion',					'Resources\ExcepcionController', 						$resource_actions);

	Route::post(	'FBCampaign/ds',			[	'uses' => 'Resources\FBCampaignController@ds',					'as' => 'resource.FBCampaign.ds'			]);
	Route::resource('FBCampaign',					'Resources\FBCampaignController', 						$resource_actions);

	Route::post(	'flotchart/getOfertas',		[	'uses' => 'Resources\FlotChartController@getOfertas', 			'as' => 'resource.flotchart.getOfertas'		]);
	Route::post(	'flotchart/getPublicaciones',[	'uses' => 'Resources\FlotChartController@getPublicaciones', 	'as' => 'resource.flotchart.getPublicaciones']);
	Route::post(	'flotchart/getSubscribers',	[	'uses' => 'Resources\FlotChartController@getSubscribers', 		'as' => 'resource.flotchart.getSubscribers'	]);
	Route::post(	'flotchart/getOrdenes',		[	'uses' => 'Resources\FlotChartController@getOrdenes', 			'as' => 'resource.flotchart.getOrdenes'		]);

	Route::post(	'galeria/ds',				[	'uses' => 'Resources\GaleriaController@ds',						'as' => 'resource.galeria.ds'				]);
	Route::resource('galeria',					'Resources\GaleriaController', 						$resource_actions);

	Route::post(	'gasto/ds', 				[	'uses' => 'Resources\GastoController@ds',						'as' => 'resource.gasto.ds'					]);
	Route::resource('gasto',						'Resources\GastoController', 							$resource_actions);

	Route::post(	'imagen/ds',				[	'uses' => 'Resources\ImagenController@ds', 						'as' => 'resource.imagen.ds'				]);
	Route::resource('imagen',						'Resources\ImagenController', 							$resource_actions);

	Route::post(	'lista/ds',					[	'uses' => 'Resources\ListaController@ds',						'as' => 'resource.lista.ds'					]);
	Route::resource('lista',						'Resources\ListaController',							$resource_actions);

	Route::post(	'listaItem/ds',				[	'uses' => 'Resources\ListaItemController@ds',					'as' => 'resource.listaItem.ds'				]);
	Route::resource('listaItem',					'Resources\ListaItemController', 						$resource_actions);

	Route::post(	'marca/ds',					[	'uses' => 'Resources\MarcaController@ds',						'as' => 'resource.marca.ds'					]);
	Route::resource('marca',						'Resources\MarcaController', 							$resource_actions);

	Route::post(	'modelo/ds',				[	'uses' => 'Resources\ModeloController@ds',						'as' => 'resource.modelo.ds'				]);
	Route::resource('modelo',						'Resources\ModeloController', 							$resource_actions);

	Route::post(	'metatag/ds',				[	'uses' => 'Resources\MetatagController@ds',						'as' => 'resource.metatag.ds'				]);
	Route::resource('metatag',					'Resources\MetatagController', 						$resource_actions);

	Route::post(	'newsletter/ds',			[	'uses' => 'Resources\NewsletterController@ds',					'as' => 'resource.newsletter.ds'			]);
	Route::resource('newsletter',					'Resources\NewsletterController', 						$resource_actions);

	Route::post(	'noticia/ds',				[	'uses' => 'Resources\NoticiaController@ds', 					'as' => 'resource.noticia.ds'				]);
	Route::resource('noticia',					'Resources\NoticiaController', 						$resource_actions);

	Route::post(	'oferta/ds',				[	'uses' => 'Resources\OfertaController@ds', 						'as' => 'resource.oferta.ds'				]);
	Route::post(	'oferta/getFlotData',		[	'uses' => 'Resources\OfertaController@getFlotData',				'as' => 'resource.oferta.getFlotData'		]);
	Route::resource('oferta',						'Resources\OfertaController', 							$resource_actions);

	Route::post(	'orden/ds',					[	'uses' => 'Resources\OrdenController@ds',						'as' => 'resource.orden.ds'					]);
	Route::resource('orden',						'Resources\OrdenController', 							$resource_actions);

	Route::post(	'permiso/ds',				[	'uses' => 'Resources\PermisoController@ds',						'as' => 'resource.permiso.ds'				]);
	Route::resource('permiso',					'Resources\PermisoController', 						$resource_actions);

	Route::post(	'precio/ds',				[	'uses' => 'Resources\PrecioController@ds',						'as' => 'resource.precio.ds'				]);
	Route::resource('precio',						'Resources\PrecioController', 							$resource_actions);

	Route::post(	'producto/{id}/update_tags',[	'uses' => 'Resources\ProductoController@update_tags',			'as' => 'resource.producto.update_tags'		]);
	Route::post(	'producto/ds',				[	'uses' => 'Resources\ProductoController@ds',					'as' => 'resource.producto.ds'				]);
	Route::post(	'producto/setActividades',	[	'uses' => 'Resources\ProductoController@setActividades',		'as' => 'resource.producto.setActividades'	]);
	Route::resource('producto',					'Resources\ProductoController', 						$resource_actions);

	Route::post(	'productoItem/ds',			[	'uses' => 'Resources\ProductoItemController@ds',				'as' => 'resource.productoItem.ds'			]);
	Route::resource('productoItem',				'Resources\ProductoItemController', 					$resource_actions);

	Route::post(	'proveedor/ds',				[	'uses' => 'Resources\ProveedorController@ds',					'as' => 'resource.proveedor.ds'				]);
	Route::resource('proveedor',					'Resources\ProveedorController', 						$resource_actions);


	Route::post(	'proveedorContacto/ds',		[	'uses' => 'Resources\ProveedorContactoController@ds',			'as' => 'resource.proveedorContacto.ds'		]);
	Route::resource('proveedorContacto',			'Resources\ProveedorContactoController', 				$resource_actions);

	Route::post(	'publicacion/ds',			[	'uses' => 'Resources\PublicacionController@ds',						'as' => 'resource.publicacion.ds'		]);
	Route::resource('publicacion',				'Resources\PublicacionController', 					$resource_actions);


	Route::post(	'role/ds',					[	'uses' => 'Resources\RoleController@ds',						'as' => 'resource.role.ds'					]);
	Route::post(	'role/guardarRolePermiso',	[	'uses' => 'Resources\RoleController@guardarRolePermiso',		'as' => 'resource.role.guardarRolePermiso'	]);
	Route::resource('role',						'Resources\RoleController',							$resource_actions);

	Route::post(	'searchAlert/ds',			[	'uses' => 'Resources\SearchAlertController@ds',					'as' => 'resource.searchAlert.ds'			]);
	Route::resource('searchAlert',				'Resources\SearchAlertController',						$resource_actions);

	Route::post(	'subscripcion/ds',			[	'uses' => 'Resources\SubscripcionController@ds',				'as' => 'resource.subscripcion.ds'			]);
	Route::resource('subscripcion',				'Resources\SubscripcionController', 					$resource_actions);

	Route::post(	'tag/ds',					[	'uses' => 'Resources\TagController@ds',							'as' => 'resource.tag.ds'					]);
	Route::resource('tag',						'Resources\TagController',								$resource_actions);

	Route::post(	'template/ds',				[	'uses' => 'Resources\TemplateController@ds',					'as' => 'resource.template.ds'				]);
	Route::resource('template',					'Resources\TemplateController',						$resource_actions);

	Route::post(	'transaccion/ds',			[	'uses' => 'Resources\TransaccionController@ds',					'as' => 'resource.transaccion.ds'			]);
	Route::resource('transaccion',				'Resources\TransaccionController',						$resource_actions);


	Route::post(	'transporte/ds',			[	'uses' => 'Resources\TransporteController@ds',					'as' => 'resource.transporte.ds'			]);
	Route::resource('transporte',					'Resources\TransporteController', 						$resource_actions);

	Route::post(	'usuario/ds',				[	'uses' => 'Resources\UsuarioController@ds',						'as' => 'resource.usuario.ds'				]);
	Route::post(	'usuario/{id}/restore',		[	'uses' => 'Resources\UsuarioController@restore',				'as' => 'resource.usuario.restore'			]);
	Route::resource('usuario',					'Resources\UsuarioController',							$resource_actions);

	Route::post(	'ubicacion/ds',				[	'uses' => 'Resources\UbicacionController@ds',					'as' => 'resource.ubicacion.ds'				]);
	Route::resource('ubicacion',					'Resources\UbicacionController',						$resource_actions);
});



$adminRoutes = function() {
//	Route::get('/', function () {
//		return view('pages/dashboard-v1');
//	});

	$i_s_c_e = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit'
		]
	];

	$i_c_e_u_d = [
		'as' => 'admin',
		'only' => [
			'index',
			'create',
			'edit',
			'update',
			'destroy'
		]
	];

	$i_s_c_e_u = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit',
			'update',
		]
	];

	Route::get(	'/check_product_thumbs',								[	'uses' => 'Admin\IndexController@check_product_thumbs', 					'as' => 'admin.check_product_thumbs'				]);
	Route::get(	'/auth_as/{id}',										[	'uses' => 'Admin\IndexController@auth_as', 									'as' => 'admin.auth_as'								]);
	Route::post('/changeLanguage',										[	'uses' => 'Admin\IndexController@changeLanguage',							'as' => 'admin.changeLanguage'						]);

app/Http/Controllers/Admin/MarcaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Marca;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MarcaController extends Controller {

	public function __construct() {
		$this->middleware('auth:empleados');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		return view('admin.pages.marca.index', []);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

		return view('admin.pages.marca.create', []);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		$marca = Marca::findOrFail($id);

		return view('admin.pages.marca.show', [
			'marca' => $marca,
		]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {

		$marca = Marca::findOrFail($id);

		return view('admin.pages.marca.edit', [
			'marca' => $marca,
		]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		//
	}
}

app/Http/Controllers/Resources/MarcaController.php
<?php

namespace App\Http\Controllers\Resources;

use App\Models\Marca;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MarcaController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$this->validate($request, [
			'nombre'        => '',
			'descripcion'   => '',
			
		]);

		//$marca = Marca::create($request->all());
		$marca = new Marca();
		$marca->nombre        = trim($request['nombre']);
		$marca->descripcion   = trim($request['descripcion']);
		
		$marca->save();

		if($marca){
			$response = Array(
				'result' => true,
				'message' => 'Registro creado.',
				'data' => $marca
			);
		} else {
			$response = Array(
				'result' => false,
				'message' => 'No se pudo crear el registro.',
				'data' => $request->all()
			);
		}

		return response()->json($response);

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$this->validate($request, [
			'nombre'        => '',
			'descripcion'   => '',
			
		]);

		$marca = Marca::findOrFail($id);

		if( isset($request['nombre']) )       $marca->nombre        = trim($request['nombre']);
		if( isset($request['descripcion']) )  $marca->descripcion   = trim($request['descripcion']);
		
		$marca->save();
		$response = Array(
			'result' => true,
			'message' => 'Registro guardado.',
			'data' => $marca
		);
		return response()->json($response);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Request $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Request $request, $id) {

		if($id != 0){
			$ids = [$id];
		} else {
			$this->validate($request, [
				'ids' => 'required|array'
			]);
			$ids = $request['ids'];
		}

		$count = Marca::destroy($ids);

		if($count == count($ids)){
			$result = Array(
				'result' => true,
				'message' => 'Registro(s) eliminado(s) correctamente.',
				'data' => $request->all()
			);
		} else {
			$result = Array(
				'result' => false,
				'message' => 'No se pudieron eliminar el/los registro(s). Eliminados: '.$count.' de: '.count($ids),
				'data' => $request->all()
			);
		}
		return response()->json($result);
	}

	// ---------- CUSTOM

	public function restore(Request $request) {
		$this->validate($request, [
			'ids' => 'required|array'
		]);
		$ids = $request['ids'];

		$count = 0;
		$marcas = Marca::whereIn('id', $ids)->withTrashed()->get();
		foreach($marcas as $marca) {
			if($marca->restore()) {
				$count++;
			}
		}

		if($count == count($ids)){
			$result = Array(
				'result' => true,
				'message' => 'Registro(s) restaurados(s) correctamente.',
				'data' => $request->all()
			);
		} else {
			$result = Array(
				'result' => false,
				'message' => 'No se pudieron retaurar el/los registro(s). Eliminados: '.$count.' de: '.count($ids),
				'data' => $request->all()
			);
		}
		return response()->json($result);
	}

	public function ds(Request $request){
		if(isset($request['draw'])) {	// llamada DataTable
			/**
			 * Parametro $request['page'] no existe (no es provisto por el DataTable), pero es necesario para el paginador
			 * lo calculamos a partir de los parametros 'start' y 'length' provistos por el DataTable
			 */
			$request['page'] = 1 + ($request['start']/$request['length']);
		}

		$builder = Marca::select(['*']);

		$searchValue = '';
		if(isset($request['draw'])) {	// llamada DataTable
			if($request['search']['value'] != ''){
				$searchValue = $request['search']['value'];
			}
		} else {						// llamada Select2
			if(isset($request['q'])){
				$searchValue = $request['q'];
			}
		}

		if($searchValue != ''){
			$builder->where('nombre', 'like', '%'.$searchValue.'%');
		}

		if(isset($request['draw'])) {	// llamada DataTable
			$builder->orderBy('created_at', 'desc');
			$ds = $builder->paginate($request['length'], ['*']);
		} else {		// llamada Select2
			return $builder->paginate($request['length'], ['*']);
		}

		/**
		 * Los campos: data, recordsTotal, recordsFiltered, draw
		 * son necesarios para que el datatable pueda
		 * interpretar la informacion de la tabla
		 */
		$response = [
			'result' => true,
			'message' => '',
			'data' => $ds->items(),
			'recordsTotal' => $ds->total(),
			'recordsFiltered' => $ds->total(),
			'draw' => $request['draw']
		];

		return response()->json($response);
	}

}

resources/views/admin/pages/marca/index.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@section('title', ' Marcas')

@push('css')
<link href="/assets/plugins/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<link href="/assets/plugins/datatables/css/responsive/responsive.bootstrap4.css" rel="stylesheet" />
@endpush

@section('content')
	<!-- begin breadcrumb -->
	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
		<li class="breadcrumb-item active"> Marcas</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header"> Marcas <small></small></h1>
	<!-- end page-header -->

	<!-- begin panel -->
	<div class="panel panel-inverse">
		<!-- begin panel-heading -->
		<div class="panel-heading">
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
				{{--<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>--}}
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
				{{--<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>--}}
			</div>
			<h4 class="panel-title"> Marcas</h4>
		</div>
		<!-- end panel-heading -->
		<!-- begin panel-body -->
		<div class="panel-body">
			<div class="form-group">
				<a class="btn btn-primary btn-sm" href="javascript:;" onclick="marcaCreate()"><i class="fa fa-plus"></i> Crear</a>
				<a class="btn btn-primary btn-sm" href="javascript:;" onclick="marcaDelete()"><i class="fa fa-trash"></i> Eliminar</a>
			</div>
			<table id="data-table" class="table table-striped table-bordered"></table>
		</div>
		<!-- end panel-body -->
	</div>
	<!-- end panel -->
@endsection

@push('scripts')
<script src="/assets/plugins/datatables/js/jquery.dataTables.js"></script>
<script src="/assets/plugins/datatables/js/dataTables.bootstrap4.js"></script>
<script src="/assets/plugins/datatables/js/responsive/dataTables.responsive.js"></script>
<script src="/assets/plugins/datatables/js/responsive/responsive.bootstrap4.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

{{--<script src="/assets/js/demo/table-manage-default.demo.js"></script>--}}
<script>

	var datatable = null;
	var modal = null;
	var estados = '';

	$(document).ready(function(){
		initDataTable();
	});

	function initDataTable(){
		if (!$.fn.DataTable.isDataTable('#data-table')) {
			datatable = $('#data-table').DataTable({
				lengthMenu: [5, 10, 30, 50, 100, 150],
				pageLength: 50,
//				dom: 'Bfrtip',
				buttons: [
					{
						text: 'Nuevo',
						action: function(e, dt, node, config){
							alert('Button activated');
						}
					}
				],
				ajax: {
					url: '{{ route('resource.marca.ds') }}',
					dataSrc: 'data',
					method: 'POST',
					'headers': {
						'X-CSRF-TOKEN': '{{ csrf_token() }}'
					},
					data: function (d){ // Procesa datos enviados
						// d.element = $('#element').val();
						// ...
					},
					dataFilter: function(data){ // Procesa datos recibidos
						return data;
//						var data = JSON.parse(data);
//						for(var i = 0 ; i < data.data.length; i++){
//							// ...
//						}
//						return JSON.stringify( data );
					}
				},
				columns: [
					{ data: 'id', title: 'Id'},
					{ data: 'nombre', title: 'Nombre'},
					{ data: 'descripcion', title: 'Descripcion'},
					{ data: 'created_at', title: 'Created_at'},

					{ title: ''},
					{ title: '<input type="checkbox" id="idsChecker" value="" />'},
					// ...
				],
				columnDefs: [
					@php $counter = 0 @endphp
					{
						// id,
						targets: {{ $counter++ }},
						classname: 'text-center',
						width: '30px',
						render: function( data, type, row ) {
							return '<a href="javascript:;" onclick="marcaShow('+ row.id +')">'+ data +'</i></a>';
						}
					},{
						// nombre,
						targets: {{ $counter++ }},
						render: function( data, type, row ) {
							return '<a href="javascript:;" onclick="marcaShow('+ row.id +')">'+ data +'</i></a>';
						}
					},{
						// descripcion,
						targets: {{ $counter++ }},
						render: function( data, type, row ) {
							return data;
						}
					},{
						// created_at,
						targets: {{ $counter++ }},
						classname: 'text-center',
						width: '100px',
						render: function( data, type, row ) {
							return format_datetime(data);
						}
					}, {
						targets: {{ $counter++ }},
						className: 'text-center with-btn',
						width: '20px',
						render: function(data, type, row){
							var html = '';
							html += '<a href="javascript:;" onclick="marcaEdit('+ row.id +')" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a>';
							return html;
						}
					}, {
						targets: {{ $counter++ }},
						className: 'text-center',
						width: '20px',
						render: function(data, type, row){
							return '<input type="checkbox" class="chkId" name="id[]" value="'+row.id+'" />';
						}
					}
				],
				fixedHeader: {
					header: true,
					headerOffset: $('#header').height()
				},
				bSort : false,
				bAutoWidth: false,
				processing: true,
				serverSide: true,
				responsive: true,
				fixedColumns: true
			}).on('draw.dt', function(){
				$('#idsChecker').on('change', function(e){
					$('.chkId').prop('checked', $(this).prop('checked'));
				});
			});
		} else {
			datatable.ajax.reload();
		}

	}

	function marcaShow(id){
		var url = '{{ route('admin.marca.show', [0]) }}';
		url = url.replace(0, id);
		var modal = openModal(url, 'Marca', null, {
			'size': 'modal-lg'
		});
	}

	function marcaCreate(){
		var url = '{{ route('admin.marca.create') }}';
		var modal = openModal(url, 'Nuevo Marca', null, { size:'modal-lg' });
		setModalHandler('formMarcaCreate:success', function(){
			dismissModal(modal);
			datatable.ajax.reload();
		});
	}

	function marcaEdit(id){
		var url = '{{ route('admin.marca.edit', 'idRecord') }}';
		url = url.replace('idRecord', id);
		var modal = openModal(url, 'Editar Marca', null, { size:'modal-lg' });
		setModalHandler('formMarcaEdit:success', function(){
			dismissModal(modal);
			datatable.ajax.reload(null, false);
		});
	}

	function marcaDelete( id ){
		var ids = [];

		if ( id !== undefined ) {
			ids = [ id ];
		} else {
			$('.chkId').each(function() {
				if($(this).prop('checked')){
					ids.push($(this).val());
				}
			});
			if(ids.length === 0){
				alert("Debe seleccionar al menos 1 registro.");
				return false;
			}
		}

		swal({
			text: 'Está seguro que desea eliminar los registros seleccionados?',
			icon: 'warning',
			buttons: {
				cancel: 'No',
				ok: 'Si'
			},
			dangerMode: true
		}).then(function(response) {
			if (response === 'ok') {
				var url = '{{ route('resource.marca.destroy', [0]) }}';
				ajaxDelete(url, ids, function(){
					swal('Registros eliminados', { icon: "success" });
					datatable.ajax.reload(null, false);
				});
			}
		});
	}

</script>
@endpush