routes/web.php
	Route::post('calendario/ds',				[	'uses' => 'Resources\CalendarioController@ds',					'as' => 'resource.calendario.ds'			]);
	Route::resource('calendario', 				'Resources\CalendarioController', 						$resource_actions);

	Route::post(	'categoria/ds',				[	'uses' => 'Resources\CategoriaController@ds',					'as' => 'resource.categoria.ds'				]);
	Route::resource('categoria',					'Resources\CategoriaController',						$resource_actions);

	Route::post(	'categoryDefinition/ds',	[	'uses' => 'Resources\CategoryDefinitionController@ds',			'as' => 'resource.categoryDefinition.ds'	]);
	Route::resource('categoryDefinition',			'Resources\CategoryDefinitionController',				$resource_actions);

	Route::post(	'cliente/ds',				[	'uses' => 'Resources\ClienteController@ds',						'as' => 'resource.cliente.ds'				]);
	Route::resource('cliente',					'Resources\ClienteController',							$resource_actions);

	Route::post(	'comentario/ds',			[	'uses' => 'Resources\ComentarioController@ds',					'as' => 'resource.comentario.ds'			]);
	Route::resource('comentario',					'Resources\ComentarioController',						$resource_actions);

	Route::post(	'configuracion/ds',			[	'uses' => 'Resources\ConfiguracionController@ds',				'as' => 'resource.configuracion.ds'			]);
	Route::resource('configuracion',				'Resources\ConfiguracionController',					$resource_actions);

	Route::post(	'cotizacion/ds',			[	'uses' => 'Resources\CotizacionController@ds',					'as' => 'resource.cotizacion.ds'			]);
	Route::resource('cotizacion',					'Resources\CotizacionController',						$resource_actions);

	Route::post(	'destino/ds',				[	'uses' => 'Resources\DestinoController@ds', 					'as' => 'resource.destino.ds'				]);
	Route::resource('destino',					'Resources\DestinoController', 						$resource_actions);

	Route::post(	'excepcion/ds',				[	'uses' => 'Resources\ExcepcionController@ds', 					'as' => 'resource.excepcion.ds'				]);
	Route::resource('excepcion',					'Resources\ExcepcionController', 						$resource_actions);

	Route::post(	'FBCampaign/ds',			[	'uses' => 'Resources\FBCampaignController@ds',					'as' => 'resource.FBCampaign.ds'			]);
	Route::resource('FBCampaign',					'Resources\FBCampaignController', 						$resource_actions);

	Route::post(	'flotchart/getOfertas',		[	'uses' => 'Resources\FlotChartController@getOfertas', 			'as' => 'resource.flotchart.getOfertas'		]);
	Route::post(	'flotchart/getPublicaciones',[	'uses' => 'Resources\FlotChartController@getPublicaciones', 	'as' => 'resource.flotchart.getPublicaciones']);
	Route::post(	'flotchart/getSubscribers',	[	'uses' => 'Resources\FlotChartController@getSubscribers', 		'as' => 'resource.flotchart.getSubscribers'	]);
	Route::post(	'flotchart/getOrdenes',		[	'uses' => 'Resources\FlotChartController@getOrdenes', 			'as' => 'resource.flotchart.getOrdenes'		]);

	Route::post(	'galeria/ds',				[	'uses' => 'Resources\GaleriaController@ds',						'as' => 'resource.galeria.ds'				]);
	Route::resource('galeria',					'Resources\GaleriaController', 						$resource_actions);

	Route::post(	'gasto/ds', 				[	'uses' => 'Resources\GastoController@ds',						'as' => 'resource.gasto.ds'					]);
	Route::resource('gasto',						'Resources\GastoController', 							$resource_actions);

	Route::post(	'imagen/ds',				[	'uses' => 'Resources\ImagenController@ds', 						'as' => 'resource.imagen.ds'				]);
	Route::resource('imagen',						'Resources\ImagenController', 							$resource_actions);

	Route::post(	'lista/ds',					[	'uses' => 'Resources\ListaController@ds',						'as' => 'resource.lista.ds'					]);
	Route::resource('lista',						'Resources\ListaController',							$resource_actions);

	Route::post(	'listaItem/ds',				[	'uses' => 'Resources\ListaItemController@ds',					'as' => 'resource.listaItem.ds'				]);
	Route::resource('listaItem',					'Resources\ListaItemController', 						$resource_actions);

	Route::post(	'marca/ds',					[	'uses' => 'Resources\MarcaController@ds',						'as' => 'resource.marca.ds'					]);
	Route::resource('marca',						'Resources\MarcaController', 							$resource_actions);

	Route::post(	'modelo/ds',				[	'uses' => 'Resources\ModeloController@ds',						'as' => 'resource.modelo.ds'				]);
	Route::resource('modelo',						'Resources\ModeloController', 							$resource_actions);

	Route::post(	'metatag/ds',				[	'uses' => 'Resources\MetatagController@ds',						'as' => 'resource.metatag.ds'				]);
	Route::resource('metatag',					'Resources\MetatagController', 						$resource_actions);

	Route::post(	'newsletter/ds',			[	'uses' => 'Resources\NewsletterController@ds',					'as' => 'resource.newsletter.ds'			]);
	Route::resource('newsletter',					'Resources\NewsletterController', 						$resource_actions);

	Route::post(	'noticia/ds',				[	'uses' => 'Resources\NoticiaController@ds', 					'as' => 'resource.noticia.ds'				]);
	Route::resource('noticia',					'Resources\NoticiaController', 						$resource_actions);

	Route::post(	'oferta/ds',				[	'uses' => 'Resources\OfertaController@ds', 						'as' => 'resource.oferta.ds'				]);
	Route::post(	'oferta/getFlotData',		[	'uses' => 'Resources\OfertaController@getFlotData',				'as' => 'resource.oferta.getFlotData'		]);
	Route::resource('oferta',						'Resources\OfertaController', 							$resource_actions);

	Route::post(	'orden/ds',					[	'uses' => 'Resources\OrdenController@ds',						'as' => 'resource.orden.ds'					]);
	Route::resource('orden',						'Resources\OrdenController', 							$resource_actions);

	Route::post(	'permiso/ds',				[	'uses' => 'Resources\PermisoController@ds',						'as' => 'resource.permiso.ds'				]);
	Route::resource('permiso',					'Resources\PermisoController', 						$resource_actions);

	Route::post(	'precio/ds',				[	'uses' => 'Resources\PrecioController@ds',						'as' => 'resource.precio.ds'				]);
	Route::resource('precio',						'Resources\PrecioController', 							$resource_actions);

	Route::post(	'producto/{id}/update_tags',[	'uses' => 'Resources\ProductoController@update_tags',			'as' => 'resource.producto.update_tags'		]);
	Route::post(	'producto/ds',				[	'uses' => 'Resources\ProductoController@ds',					'as' => 'resource.producto.ds'				]);
	Route::post(	'producto/setActividades',	[	'uses' => 'Resources\ProductoController@setActividades',		'as' => 'resource.producto.setActividades'	]);
	Route::resource('producto',					'Resources\ProductoController', 						$resource_actions);

	Route::post(	'productoItem/ds',			[	'uses' => 'Resources\ProductoItemController@ds',				'as' => 'resource.productoItem.ds'			]);
	Route::resource('productoItem',				'Resources\ProductoItemController', 					$resource_actions);

	Route::post(	'proveedor/ds',				[	'uses' => 'Resources\ProveedorController@ds',					'as' => 'resource.proveedor.ds'				]);
	Route::resource('proveedor',					'Resources\ProveedorController', 						$resource_actions);


	Route::post(	'proveedorContacto/ds',		[	'uses' => 'Resources\ProveedorContactoController@ds',			'as' => 'resource.proveedorContacto.ds'		]);
	Route::resource('proveedorContacto',			'Resources\ProveedorContactoController', 				$resource_actions);

	Route::post(	'publicacion/ds',			[	'uses' => 'Resources\PublicacionController@ds',						'as' => 'resource.publicacion.ds'		]);
	Route::resource('publicacion',				'Resources\PublicacionController', 					$resource_actions);


	Route::post(	'role/ds',					[	'uses' => 'Resources\RoleController@ds',						'as' => 'resource.role.ds'					]);
	Route::post(	'role/guardarRolePermiso',	[	'uses' => 'Resources\RoleController@guardarRolePermiso',		'as' => 'resource.role.guardarRolePermiso'	]);
	Route::resource('role',						'Resources\RoleController',							$resource_actions);

	Route::post(	'searchAlert/ds',			[	'uses' => 'Resources\SearchAlertController@ds',					'as' => 'resource.searchAlert.ds'			]);
	Route::resource('searchAlert',				'Resources\SearchAlertController',						$resource_actions);

	Route::post(	'subscripcion/ds',			[	'uses' => 'Resources\SubscripcionController@ds',				'as' => 'resource.subscripcion.ds'			]);
	Route::resource('subscripcion',				'Resources\SubscripcionController', 					$resource_actions);

	Route::post(	'tag/ds',					[	'uses' => 'Resources\TagController@ds',							'as' => 'resource.tag.ds'					]);
	Route::resource('tag',						'Resources\TagController',								$resource_actions);

	Route::post(	'template/ds',				[	'uses' => 'Resources\TemplateController@ds',					'as' => 'resource.template.ds'				]);
	Route::resource('template',					'Resources\TemplateController',						$resource_actions);

	Route::post(	'transaccion/ds',			[	'uses' => 'Resources\TransaccionController@ds',					'as' => 'resource.transaccion.ds'			]);
	Route::resource('transaccion',				'Resources\TransaccionController',						$resource_actions);


	Route::post(	'transporte/ds',			[	'uses' => 'Resources\TransporteController@ds',					'as' => 'resource.transporte.ds'			]);
	Route::resource('transporte',					'Resources\TransporteController', 						$resource_actions);

	Route::post(	'usuario/ds',				[	'uses' => 'Resources\UsuarioController@ds',						'as' => 'resource.usuario.ds'				]);
	Route::post(	'usuario/{id}/restore',		[	'uses' => 'Resources\UsuarioController@restore',				'as' => 'resource.usuario.restore'			]);
	Route::resource('usuario',					'Resources\UsuarioController',							$resource_actions);

	Route::post(	'ubicacion/ds',				[	'uses' => 'Resources\UbicacionController@ds',					'as' => 'resource.ubicacion.ds'				]);
	Route::resource('ubicacion',					'Resources\UbicacionController',						$resource_actions);
});



$adminRoutes = function() {
//	Route::get('/', function () {
//		return view('pages/dashboard-v1');
//	});

	$i_s_c_e = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit'
		]
	];

	$i_c_e_u_d = [
		'as' => 'admin',
		'only' => [
			'index',
			'create',
			'edit',
			'update',
			'destroy'
		]
	];

	$i_s_c_e_u = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit',
			'update',
		]
	];

app/Models/Lista.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Lista
 *
 * @property int $id
 * @property int|null $idPadre
 * @property string|null $nombre
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ListaItem[] $Items
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ListaItem[] $ListaItems
 * @property-read \App\Models\Lista|null $Padre
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Lista whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Lista whereIdPadre($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Lista whereNombre($value)
 * @mixin \Eloquent
 */
class Lista extends Model  {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'Lista';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
    	'idPadre',
		'nombre'
	];

    public $timestamps = false;

    // ---------- CONSTANTS

	const SEXO = 1;
	const CLIENTE_TIPO = 2;
	const CLIENTE_ESTADO = 3;
	const EMPLEADO_TIPO = 4;
	const EMPLEADO_ESTADO = 5;
	const ESTADO_CIVIL = 6;
	const GALERIA_TIPO = 7;
	const GALERIA_ESTADO = 8;
	const HORARIO = 9;
	const DIMENSION = 10;
	const RECURSO = 11;
	const MARCA = 12;
	const MODELO = 13;
	const ORDEN_TIPO = 14;
	const ORDEN_ESTADO = 15;
	const PRODUCTO_TIPO = 16;
	const PRODUCTO_ESTADO = 17;
	const PROVEEDOR_TIPO = 18;
	const PROVEEDOR_ESTADO = 19;
	const PROVEEDOR_CONTACTO_TIPO = 20;
	const PROVEEDOR_CONTACTO_ESTADO = 21;
	const PUBLICIDAD_ESTADO = 22;
	const PUBLICIDAD_ESQUEMA_TIPO = 23;
	const USUARIO_TIPO = 24;
	const USUARIO_ESTADO = 25;
	const MONEDA = 26;
	const PUBLICACION_ESTADO = 27;
	const CONSULTA_EXTERNA_ESTADO = 28;
	const BANNER_TIPO = 29;
	const TEMPLATE_TIPO = 30;
	const MODULO = 31;
	const PAGO_TIPO = 32;
	const PRODUCTOITEM_DISPONIBILIDAD = 33;
	const SUBSCRIPCION_TIPO = 34;
	const MONEDA_USO_INTERNO = 35;
	const GASTO_TIPO = 36;
	const TRANSACCION_TIPO = 37;
	const TRANSACCION_ESTADO = 38;
	const UBICACION_TIPO = 39;
	const CONSULTA_EXTERNA_TIPO = 40;


	// ---------- RELATIONSHIPS

	public function ListaItems() {
		return $this->hasMany('App\Models\ListaItem', 'idLista');
	}

	public function Items() {
		return $this->hasMany('App\Models\ListaItem', 'idLista');
	}

	public function Padre() {
		return $this->belongsTo('App\Models\Lista', 'idPadre');
	}

}

app/Http/Controllers/Admin/ListaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Lista;
use App\Models\ListaItem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class ListaController extends Controller {

	public function __construct(){
		$this->middleware('auth:empleados');
	}

	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        return view('admin.pages.lista.index', [
		]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {

    	return view('admin.pages.lista.create', [
		]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
		$lista = Lista::findOrFail($id);

		$listaItems = ListaItem::where('idLista', $id)->orderBy('orden')->get();

		return view('admin.pages.lista.show', [
			'lista' => $lista,
			'listaItems' => $listaItems,
		]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $lista = Lista::findOrFail($id);
		$listaItems = ListaItem::where('idLista', $id)->orderBy('orden')->get();

		return view('admin.pages.lista.edit', [
			'lista' => $lista,
			'listaItems' => $listaItems,
		]);
    }
    public function edit_alt($id) {

        $lista = Lista::findOrFail($id);
		$listaItems = ListaItem::where('idLista', $id)->orderBy('orden')->get();

		return view('admin.pages.lista.edit_alt', [
			'lista' => $lista,
			'listaItems' => $listaItems,
		]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }
}

resources/views/admin/pages/lista/create.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@push('css')

@endpush

@section('content')

	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
		<li class="breadcrumb-item"><a href="{{ route('admin.lista.index') }}">Lista</a></li>
		<li class="breadcrumb-item active">Nuevo/a lista</li>
	</ol>

	<h1 class="page-header">Nuevo Lista</h1>

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Nuevo Lista</h4>
		</div>
		<div class="panel panel-body">
			<form id="formListaCreate" method="post" class="form-horizontal row">


				<div class="form-group col-md-12 col-sm-12 row m-b-15">
					<label class="col-form-label col-2">Nombre</label>
					<div class="col-10">
						{!! Form::text('nombre', '', [
							'id' => 'nombre',
							'placeholder' => 'Nombre',
							'class' => 'form-control',
						]) !!}
					</div>
				</div>

				{{--<div class="form-group col-md-6 col-sm-12 row m-b-15">--}}
					{{--<label class="col-form-label col-4">Id Padre <br><small>no modificar</small></label>--}}
					{{--<div class="col-8">--}}
						{{--{!! Form::number('idPadre', 0, [--}}
							{{--'id' => 'idPadre',--}}
							{{--'placeholder' => 'Id Padre',--}}
							{{--'class' => 'form-control',--}}
						{{--]) !!}--}}
					{{--</div>--}}
				{{--</div>--}}

			</form>
			<div class="form-group row">
				<div class="col-lg-12 text-right">
					<a class="btn btn-white btn-sm" data-dismiss="modal" href="javascript:;" onclick="listaCancel()">Cerrar</a>
					<a class="btn btn-primary btn-sm" href="javascript:;" onclick="listaSave()" >Guardar</a>
				</div>
			</div>
		</div>
	</div>

@stop

@push('scripts')



<script>

@if($isAjaxRequest)
    formInit();
@else
    $(function(){ formInit(); });
@endif

$( "#formListaCreate" ).submit(function( event ) {
	listaSave();
	event.preventDefault();
});

function listaSave(){
	var url = '{{ route('resource.lista.store') }}';
	ajaxPost(url, {
		idPadre: 		0, //$('#formListaCreate #idPadre').val(),
		nombre: 		$('#formListaCreate #nombre').val()
	}, function(){
		$(document).trigger('formListaCreate:success');
	});
}

function listaCancel(){
	@if($isAjaxRequest)
		$(document).trigger('formListaCreate:cancel');
	@else
		redirect('{{ route('admin.lista.index')  }}');
	@endif
}

function formInit(){



}

</script>
@endpush

resources/views/admin/pages/lista/edit.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@push('css')
<link href="/assets/plugins/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<link href="/assets/plugins/datatables/css/responsive/responsive.bootstrap4.css" rel="stylesheet" />
@endpush

@section('content')

	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
		<li class="breadcrumb-item"><a href="{{ route('admin.lista.index') }}">Lista</a></li>
		<li class="breadcrumb-item active">Actualizando: {{ $lista->id }}</li>
	</ol>

	<h1 class="page-header">Actualizando Lista</h1>

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Nuevo Lista</h4>
		</div>
		<div class="panel panel-body">
			<form id="formListaEdit" method="post" class="form-horizontal row">

				<div class="form-group col-md-12 col-sm-12 row m-b-15">
					<label class="col-form-label col-2">Nombre</label>
					<div class="col-10">
						{!! Form::text('nombre', $lista->nombre, [
							'id' => 'nombre',
							'placeholder' => 'Nombre',
							'class' => 'form-control',
						]) !!}
					</div>
				</div>
				{{--<div class="form-group col-md-6 col-sm-12 row m-b-15">--}}
					{{--<label class="col-form-label col-4">Id Padre</label>--}}
					{{--<div class="col-8">--}}
						{{--{!! Form::number('idPadre', $lista->idPadre, [--}}
							{{--'id' => 'idPadre',--}}
							{{--'placeholder' => 'Id Padre',--}}
							{{--'class' => 'form-control',--}}
						{{--]) !!}--}}
					{{--</div>--}}
				{{--</div>--}}

				<table id="dtListaItems" class="table table-condensed table-striped"></table>


			</form>
			<div class="form-group row">
				<div class="col-lg-12 text-right">
					<a class="btn btn-info btn-sm" href="javascript:;" onclick="listaItemCreate_lista()">Agregar item</a>
					<a class="btn btn-white btn-sm" data-dismiss="modal" href="javascript:;" onclick="listaCancel()">Cerrar</a>
					<a class="btn btn-primary btn-sm" href="javascript:;" onclick="listaSave()" >Guardar</a>
				</div>
			</div>
		</div>
	</div>

@stop

@push('scripts')
<script src="/assets/plugins/datatables/js/jquery.dataTables.js"></script>
<script src="/assets/plugins/datatables/js/dataTables.bootstrap4.js"></script>
<script src="/assets/plugins/datatables/js/responsive/dataTables.responsive.js"></script>
<script src="/assets/plugins/datatables/js/responsive/responsive.bootstrap4.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>


<script>

var dtListaItems = null;

@if($isAjaxRequest)
    formInit();
	initDataTable();
@else
    $(function(){
    	formInit();
		initDataTable();
    });
@endif

$( "#formListaEdit" ).submit(function( event ) {
	listaSave();
	event.preventDefault();
});

function listaSave(){
	var url = '{{ route('resource.lista.update', [ $lista->id ]) }}';
	ajaxPatch(url, {
		idPadre: 		0, //$('#formListaEdit #idPadre').val(),
		nombre: 		$('#formListaEdit #nombre').val()
	}, function(){
		$(document).trigger('formListaEdit:success');
	});
}

function listaCancel(){
	@if($isAjaxRequest)
		$(document).trigger('formListaEdit:cancel');
	@else
		redirect('{{ route('admin.lista.index')  }}');
	@endif
}

function listaItemCreate_lista(){
	var url = '{{ route('admin.listaItem.create', [ 'idLista' => $lista->id ]) }}';
	var modal = openModal(url, 'Nuevo elemento de lista', null, { size:'modal-lg' });
	setModalHandler('formListaItemCreate:success', function(){
		dismissModal(modal);
		dtListaItems.ajax.reload();
	});
}

function listaItemEdit_lista(id){
	var url = '{{ route('admin.listaItem.index') }}/'+id+'/edit';
	var modal = openModal(url, 'Editar ListaItem', null, { size:'modal-lg' });
	setModalHandler('formListaItemEdit:success', function(){
		dismissModal(modal);
		dtListaItems.ajax.reload(null, false);
	});
}

function listaItemDelete_lista(id){
	var ids = [id];

	swal({
		text: 'Está seguro que desea eliminar los registros seleccionados?',
		icon: 'warning',
		buttons: {
			cancel: 'No',
			ok: 'Si'
		},
		dangerMode: true
	}).then(function(response) {
		if (response === 'ok') {
			var url = '{{ route('resource.listaItem.destroy', [0]) }}';
			ajaxDelete(url, ids, function(){
				$(document).trigger('formListaEdit_alt:success');
				swal('Registros eliminados', { icon: "success" });
				dtListaItems.ajax.reload(null, false);
			});
		}
	});
}

function formInit(){

}

function initDataTable(){
	if (!$.fn.DataTable.isDataTable('#dtListaItems')) {
		dtListaItems = $('#dtListaItems').DataTable({
			paging: false,
			searching: false,
//				dom: 'Bfrtip',
			buttons: [
				{
					text: 'Nuevo',
					action: function(e, dt, node, config){
						alert('Button activated');
					}
				}
			],
			ajax: {
				url: '{{ route('resource.listaItem.ds') }}',
				dataSrc: 'data',
				method: 'POST',
				'headers': {
					'X-CSRF-TOKEN': '{{ csrf_token() }}'
				},
				data: function (d){ // Procesa datos enviados
					 d.idLista = {{ $lista->id }};
					// ...
				},
				dataFilter: function(data){ // Procesa datos recibidos
					return data;
//	                    var data = JSON.parse(data);
//	                    for(var i = 0 ; i < data.data.length; i++){
//	                        // ...
//	                    }
//	                    return JSON.stringify( data );
				}
			},
			columns: [
				{ data: 'texto', title: 'Texto'},
				{ data: 'valor', title: 'Valor'},
				{ data: 'orden', title: 'Orden'},

				{ title: ''},
				// ...
			],
			columnDefs: [
					@php $counter = 0 @endphp
				{
					// texto,
					targets: {{ $counter++ }},
					render: function( data, type, row ) {
						return data;
					}
				},{
					// valor,
					targets: {{ $counter++ }},
					render: function( data, type, row ) {
						return data;
					}
				},{
					// orden,
					targets: {{ $counter++ }},
					render: function( data, type, row ) {
						return data;
					}
				}, {
					targets: {{ $counter++ }},
					className: 'text-center with-btn',
					width: '20px',
					render: function(data, type, row){
						var html = '';
						html += '<a href="javascript:;" onclick="listaItemEdit_lista('+ row.id +')" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a>';
						html += '&nbsp;&nbsp;';
						html += '<a href="javascript:;" onclick="listaItemDelete_lista('+ row.id +')" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>';
						return html;
					}
				}
			],
			fixedHeader: {
				header: true,
				headerOffset: $('#header').height()
			},
			bSort : false,
			bAutoWidth: false,
			processing: true,
			serverSide: true,
			responsive: true,
			fixedColumns: true
		}).on('draw.dt', function(){
			$('#idsChecker').on('change', function(e){
				$('.chkId').prop('checked', $(this).prop('checked'));
			});
		});
	} else {
		dtListaItems.ajax.reload();
	}
}

</script>
@endpush