routes/web.php
	Route::post(	'flotchart/getSubscribers',	[	'uses' => 'Resources\FlotChartController@getSubscribers', 		'as' => 'resource.flotchart.getSubscribers'	]);
	Route::post(	'flotchart/getOrdenes',		[	'uses' => 'Resources\FlotChartController@getOrdenes', 			'as' => 'resource.flotchart.getOrdenes'		]);

	Route::post(	'galeria/ds',				[	'uses' => 'Resources\GaleriaController@ds',						'as' => 'resource.galeria.ds'				]);
	Route::resource('galeria',					'Resources\GaleriaController', 						$resource_actions);

	Route::post(	'gasto/ds', 				[	'uses' => 'Resources\GastoController@ds',						'as' => 'resource.gasto.ds'					]);
	Route::resource('gasto',						'Resources\GastoController', 							$resource_actions);

	Route::post(	'imagen/ds',				[	'uses' => 'Resources\ImagenController@ds', 						'as' => 'resource.imagen.ds'				]);
	Route::resource('imagen',						'Resources\ImagenController', 							$resource_actions);

	Route::post(	'lista/ds',					[	'uses' => 'Resources\ListaController@ds',						'as' => 'resource.lista.ds'					]);
	Route::resource('lista',						'Resources\ListaController',							$resource_actions);

	Route::post(	'listaItem/ds',				[	'uses' => 'Resources\ListaItemController@ds',					'as' => 'resource.listaItem.ds'				]);
	Route::resource('listaItem',					'Resources\ListaItemController', 						$resource_actions);

	Route::post(	'marca/ds',					[	'uses' => 'Resources\MarcaController@ds',						'as' => 'resource.marca.ds'					]);
	Route::resource('marca',						'Resources\MarcaController', 							$resource_actions);

	Route::post(	'modelo/ds',				[	'uses' => 'Resources\ModeloController@ds',						'as' => 'resource.modelo.ds'				]);
	Route::resource('modelo',						'Resources\ModeloController', 							$resource_actions);

	Route::post(	'metatag/ds',				[	'uses' => 'Resources\MetatagController@ds',						'as' => 'resource.metatag.ds'				]);
	Route::resource('metatag',					'Resources\MetatagController', 						$resource_actions);

	Route::post(	'newsletter/ds',			[	'uses' => 'Resources\NewsletterController@ds',					'as' => 'resource.newsletter.ds'			]);
	Route::resource('newsletter',					'Resources\NewsletterController', 						$resource_actions);

	Route::post(	'noticia/ds',				[	'uses' => 'Resources\NoticiaController@ds', 					'as' => 'resource.noticia.ds'				]);
	Route::resource('noticia',					'Resources\NoticiaController', 						$resource_actions);

	Route::post(	'oferta/ds',				[	'uses' => 'Resources\OfertaController@ds', 						'as' => 'resource.oferta.ds'				]);
	Route::post(	'oferta/getFlotData',		[	'uses' => 'Resources\OfertaController@getFlotData',				'as' => 'resource.oferta.getFlotData'		]);
	Route::resource('oferta',						'Resources\OfertaController', 							$resource_actions);

	Route::post(	'orden/ds',					[	'uses' => 'Resources\OrdenController@ds',						'as' => 'resource.orden.ds'					]);
	Route::resource('orden',						'Resources\OrdenController', 							$resource_actions);

	Route::post(	'permiso/ds',				[	'uses' => 'Resources\PermisoController@ds',						'as' => 'resource.permiso.ds'				]);
	Route::resource('permiso',					'Resources\PermisoController', 						$resource_actions);

	Route::post(	'precio/ds',				[	'uses' => 'Resources\PrecioController@ds',						'as' => 'resource.precio.ds'				]);
	Route::resource('precio',						'Resources\PrecioController', 							$resource_actions);

	Route::post(	'producto/{id}/update_tags',[	'uses' => 'Resources\ProductoController@update_tags',			'as' => 'resource.producto.update_tags'		]);
	Route::post(	'producto/ds',				[	'uses' => 'Resources\ProductoController@ds',					'as' => 'resource.producto.ds'				]);
	Route::post(	'producto/setActividades',	[	'uses' => 'Resources\ProductoController@setActividades',		'as' => 'resource.producto.setActividades'	]);
	Route::resource('producto',					'Resources\ProductoController', 						$resource_actions);

	Route::post(	'productoItem/ds',			[	'uses' => 'Resources\ProductoItemController@ds',				'as' => 'resource.productoItem.ds'			]);
	Route::resource('productoItem',				'Resources\ProductoItemController', 					$resource_actions);

	Route::post(	'proveedor/ds',				[	'uses' => 'Resources\ProveedorController@ds',					'as' => 'resource.proveedor.ds'				]);
	Route::resource('proveedor',					'Resources\ProveedorController', 						$resource_actions);


	Route::post(	'proveedorContacto/ds',		[	'uses' => 'Resources\ProveedorContactoController@ds',			'as' => 'resource.proveedorContacto.ds'		]);
	Route::resource('proveedorContacto',			'Resources\ProveedorContactoController', 				$resource_actions);

	Route::post(	'publicacion/ds',			[	'uses' => 'Resources\PublicacionController@ds',						'as' => 'resource.publicacion.ds'		]);
	Route::resource('publicacion',				'Resources\PublicacionController', 					$resource_actions);


	Route::post(	'role/ds',					[	'uses' => 'Resources\RoleController@ds',						'as' => 'resource.role.ds'					]);
	Route::post(	'role/guardarRolePermiso',	[	'uses' => 'Resources\RoleController@guardarRolePermiso',		'as' => 'resource.role.guardarRolePermiso'	]);
	Route::resource('role',						'Resources\RoleController',							$resource_actions);

	Route::post(	'searchAlert/ds',			[	'uses' => 'Resources\SearchAlertController@ds',					'as' => 'resource.searchAlert.ds'			]);
	Route::resource('searchAlert',				'Resources\SearchAlertController',						$resource_actions);

	Route::post(	'subscripcion/ds',			[	'uses' => 'Resources\SubscripcionController@ds',				'as' => 'resource.subscripcion.ds'			]);
	Route::resource('subscripcion',				'Resources\SubscripcionController', 					$resource_actions);

	Route::post(	'tag/ds',					[	'uses' => 'Resources\TagController@ds',							'as' => 'resource.tag.ds'					]);
	Route::resource('tag',						'Resources\TagController',								$resource_actions);

	Route::post(	'template/ds',				[	'uses' => 'Resources\TemplateController@ds',					'as' => 'resource.template.ds'				]);
	Route::resource('template',					'Resources\TemplateController',						$resource_actions);

	Route::post(	'transaccion/ds',			[	'uses' => 'Resources\TransaccionController@ds',					'as' => 'resource.transaccion.ds'			]);
	Route::resource('transaccion',				'Resources\TransaccionController',						$resource_actions);


	Route::post(	'transporte/ds',			[	'uses' => 'Resources\TransporteController@ds',					'as' => 'resource.transporte.ds'			]);
	Route::resource('transporte',					'Resources\TransporteController', 						$resource_actions);

	Route::post(	'usuario/ds',				[	'uses' => 'Resources\UsuarioController@ds',						'as' => 'resource.usuario.ds'				]);
	Route::post(	'usuario/{id}/restore',		[	'uses' => 'Resources\UsuarioController@restore',				'as' => 'resource.usuario.restore'			]);
	Route::resource('usuario',					'Resources\UsuarioController',							$resource_actions);

	Route::post(	'ubicacion/ds',				[	'uses' => 'Resources\UbicacionController@ds',					'as' => 'resource.ubicacion.ds'				]);
	Route::resource('ubicacion',					'Resources\UbicacionController',						$resource_actions);
});



$adminRoutes = function() {
//	Route::get('/', function () {
//		return view('pages/dashboard-v1');
//	});

	$i_s_c_e = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit'
		]
	];

	$i_c_e_u_d = [
		'as' => 'admin',
		'only' => [
			'index',
			'create',
			'edit',
			'update',
			'destroy'
		]
	];

	$i_s_c_e_u = [
		'as' => 'admin',
		'only' => [
			'index',
			'show',
			'create',
			'edit',
			'update',
		]
	];

	Route::get(	'/check_product_thumbs',								[	'uses' => 'Admin\IndexController@check_product_thumbs', 					'as' => 'admin.check_product_thumbs'				]);
	Route::get(	'/auth_as/{id}',										[	'uses' => 'Admin\IndexController@auth_as', 									'as' => 'admin.auth_as'								]);
	Route::post('/changeLanguage',										[	'uses' => 'Admin\IndexController@changeLanguage',							'as' => 'admin.changeLanguage'						]);
	Route::get(	'/',													[	'uses' => 'Admin\IndexController@home'														]);
	Route::get(	'/login',												[	'uses' => 'AuthAdmin\LoginController@showLoginForm',						'as' => 'admin.loginForm'							]);
	Route::post('/login',												[	'uses' => 'AuthAdmin\LoginController@login',								'as' => 'admin.login'								]);
	Route::get(	'/logout',												[	'uses' => 'AuthAdmin\LoginController@logout',								'as' => 'admin.logout'								]);

	Route::get(	'/home',												[	'uses' => 'Admin\IndexController@home',										'as' => 'admin.home'								]);

	Route::resource('actividad',											'Admin\ActividadController',										$i_s_c_e);
	Route::resource('actividadTipo',										'Admin\ActividadTipoController',									$i_s_c_e);

	Route::get(	'anuncio/mapaFormularios',								[	'uses' => 'Admin\AnuncioController@mapaFormularios',						'as' => 'admin.anuncio.mapaFormularios'				]);
	Route::resource('anuncio',											'Admin\AnuncioController', 										$i_s_c_e);
	Route::resource('agenda',												'Admin\AgendaController', 											$i_s_c_e);

	Route::patch('announcementInbox/{idAnnounce}/updateCalculadora', 	[	'uses' => 'Admin\AnnouncementInboxController@updateCalculadora', 			'as' => 'admin.announcementInbox.updateCalculadora'	]);
	Route::get(	'announcementInbox/{id}/{lang?}', 						[	'uses' => 'Admin\AnnouncementInboxController@show', 						'as' => 'admin.announcementInbox.show'				]);
	Route::get(	'announcementInbox/trans_disp/{pubId}/{idTrans}', 		[	'uses' => 'Admin\AnnouncementInboxController@transporteDisponibilidad', 	'as' => 'admin.announcementInbox.transporteDisponibilidad']);
	Route::post('announcementInbox/trans_disp/{pubId}/{idTrans}', 		[	'uses' => 'Admin\AnnouncementInboxController@transporteDisponibilidad', 	'as' => 'admin.announcementInbox.transporteDisponibilidad']);
	Route::post('announcementInbox/estado',								[	'uses' => 'Admin\AnnouncementInboxController@estado', 						'as' => 'admin.announcementInbox.estado'			]);
	Route::resource('announcementInbox',									'Admin\AnnouncementInboxController',								$i_c_e_u_d);

resources/views/admin/pages/producto/create_producto_item.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@push('css')
@endpush

@section('content')

	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
		<li><a href="{{ route('admin.producto.index') }}">Productos</a></li>
		<li class="active">Nuevo Producto Item</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Nuevo Producto Item</h1>
	<!-- end page-header -->

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Nuevo ProductoItem</h4>
		</div>
		<div class="panel-body">
			<form id="formProductoItemCreate" >

                <div class="form-group row m-b-10">
	                <label class="col-form-label col-md-3">Nombre</label>
                    <div class="col-md-9">
	                    {!! Form::text('nombre', null, [
                            'id' => 'nombre',
                            'placeholder' => 'Nombre',
                            'class' => 'form-control form-control-sm m-b-5'
                        ]) !!}
                    </div>
                </div>
                <div class="form-group row m-b-10">
	                <label class="col-form-label col-md-3">Descripcion</label>
                    <div class="col-md-9">
	                    {!! Form::textarea('descripcionDetalle', null, [
                            'id' => 'descripcionDetalle',
                            'placeholder' => 'Descripcion',
                            'class' => 'form-control m-b-5',
                            'rows' => 3,
                        ]) !!}
                    </div>
                </div>
				<div class="form-group row m-b-10">
					<label class="col-form-label col-md-3">SKU</label>
					<div class="col-md-9">
						{!! Form::text('sku', null, [
							'id' => 'sku',
							'placeholder' => 'SKU',
							'class' => 'form-control form-control-sm m-b-5'
						]) !!}
					</div>
				</div>
                <div class="hr-line-dashed"></div>
                <div class="form-group row m-b-15">
                    <div class="col-lg-12 text-right">
                        <a class="btn btn-white" data-dismiss="modal" href="javascript:;">Cancelar</a>
                        <a class="btn btn-primary" href="javascript:;" onclick="guardarProductoItem()" >Guardar</a>
                    </div>
                </div>
            </form>
		</div>
	</div>

@stop

@push('scripts')
<script>
$(function(){
	initView();
});

function initView(){
//	$(".default-select2").select2();
}

function guardarProductoItem(){

	console.log("guardando");

{{--	var url = '{{ route('admin.producto.store_item', [ $producto->id ]) }}';--}}
	var url = '{{ route( 'resource.productoItem.store' ) }}';
	var form = $('#formProductoItemCreate');
	var data = {
		idProducto            : {{ $producto->id }},
		idLote                : 0,
		idDisponibilidad      : 1,
		idTipoImportacion     : 1,
		nombre                : form.find('#nombre').val(),
		descripcionPrimaria   : '', //form.find('#descripcionPrimaria'),
		descripcionDetalle    : form.find('#descripcionDetalle').val(),
		ean                   : '',
		sku                   : form.find('#sku').val(),
		precioDistribuidor    : 0, //form.find('#precioDistribuidor'),
		precioVenta           : 0, //form.find('#precioVenta'),
		monedaVenta           : '', //form.find('#monedaVenta'),
		precioPromocion       : 0, //form.find('#precioPromocion'),
		color                 : '', //form.find('#color'),
		dimension             : '', //form.find('#dimension'),
		fechaElaboracion      : '', //form.find('#fechaElaboracion'),
		fechaVencimiento      : '', //form.find('#fechaVencimiento'),
		definicion            : '', //form.find('#definicion'),
		permalink             : '', //form.find('#permalink'),
		make_item_trans       : 1
    };
	ajaxPost(url, data, function(data){
		@if($isAjaxRequest)
			$(document).trigger('formProductoItemCreate:success');
		@else
			redirect('{{ route('admin.producto.index') }}');
		@endif
	});

}

</script>
@endpush

resources/views/admin/pages/producto/create_producto_item_precio.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@push('css')
@endpush

@section('content')

	<ol class="breadcrumb pull-right">
		<li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
		<li><a href="{{ route('admin.producto.index') }}">Productos</a></li>
		<li class="active">Nuevo Producto Item</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Nuevo Producto Item</h1>
	<!-- end page-header -->

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Nuevo ProductoItem</h4>
		</div>
		<div class="panel-body">
			<form id="formProductoItemPrecioCreate" >

                <div class="form-group row m-b-10">
	                <label class="col-form-label col-md-3">USD</label>
                    <div class="col-md-9">
	                    {!! Form::number('usd', $usd , [
                            'id' => 'usd',
                            'placeholder' => 'USD',
                            'class' => 'form-control form-control-sm m-b-5'
                        ]) !!}
                    </div>
                </div>

                <div class="form-group row m-b-10">
	                <label class="col-form-label col-md-3">SEK</label>
                    <div class="col-md-9">
	                    {!! Form::number('sek', $sek , [
                            'id' => 'sek',
                            'placeholder' => 'SEK',
                            'class' => 'form-control form-control-sm m-b-5'
                        ]) !!}
                    </div>
                </div>

                <div class="form-group row m-b-10">
	                <label class="col-form-label col-md-3">CLP</label>
                    <div class="col-md-9">
	                    {!! Form::number('clp', $clp , [
                            'id' => 'clp',
                            'placeholder' => 'CLP',
                            'class' => 'form-control form-control-sm m-b-5'
                        ]) !!}
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group row m-b-15">
                    <div class="col-lg-12 text-right">
                        <a class="btn btn-white" data-dismiss="modal" href="javascript:;">Cancelar</a>
                        <a class="btn btn-primary" href="javascript:;" onclick="guardarProductoItemPrecio()" >Guardar</a>
                    </div>
                </div>
            </form>
		</div>
	</div>

@stop

@push('scripts')
<script>
$(function(){
	initView();
});

function initView(){
//	$(".default-select2").select2();
}

function guardarProductoItemPrecio(){

	console.log("guardando");

{{--	var url = '{{ route('admin.producto.store_item', [ $producto->id ]) }}';--}}
	var url = '{{ route( 'resource.precio.store' ) }}';
	var form = $('#formProductoItemPrecioCreate');
	var idTipo = {{ \App\Models\Precio::TIPO_PRECIO_VENTA }};
	var data = {
		precio: form.find('#usd').val(),
		moneda: 'usd',
		idTipo: idTipo,
		estado: 1,
		modelo_type: 'producto_item',
		modelo_id: {{ $productoItem->id }}
    };
	ajaxPost(url, data, function(data){
		data = {
			precio: form.find('#sek').val(),
			moneda: 'sek',
			idTipo: idTipo,
			estado: 1,
			modelo_type: 'producto_item',
			modelo_id: {{ $productoItem->id }}
		};
		ajaxPost(url, data, function(data){
			data = {
				precio: form.find('#clp').val(),
				moneda: 'clp',
				idTipo: idTipo,
				estado: 1,
				modelo_type: 'producto_item',
				modelo_id: {{ $productoItem->id }}
			};
			ajaxPost(url, data, function(data){
				$(document).trigger('formProductoItemPrecioCreate:success');
			});
		});
	});
}

</script>
@endpush

resources/views/admin/pages/producto/form.blade.php
@php
	$grp = 0;
	$openGroup = false;
@endphp
<div class="row">
@foreach($primaryFields as $element)

	@if($element['type'] == 'titulo1')
		@include('admin.formElements.titulo1', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'titulo2')
		@include('admin.formElements.titulo2', [
			'e' => $element,
			'group' => $grp
		])
	@endif

	@if($element['type'] == 'text')

		@if($element['key'] == 'pais_de_fabricacion')
			@include('admin.formElements.select_country', [
				'e' => $element,
			])
		@else
			@include('admin.formElements.input', [
				'e' => $element,
			])
		@endif
	@endif

	@if($element['type'] == 'number')
		@include('admin.formElements.number', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'boolean')
		@include('admin.formElements.boolean', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'multiline')
		@include('admin.formElements.text', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'select')
		@include('admin.formElements.select', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'multiselect')
		@include('admin.formElements.multiselect', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'percent10')
		@include('admin.formElements.percent10', [
			'e' => $element,
		])
	@endif

	@if($element['type'] == 'range_year')
		@include('admin.formElements.rangeYear', [
			'e' => $element,
		])
	@endif
@endforeach

</div>

	@php
		$grp = 1;
		$openGroup = false;
	@endphp
	@foreach($secondaryFields as $element)

		@if($element['type'] == 'titulo1')
			@include('admin.formElements.titulo1', [
				'e' => $element,
			])
		@endif

		@if($element['type'] == 'titulo2')
			@if($openGroup == true)
				@php echo '</div>'; @endphp
			@endif

			@include('admin.formElements.titulo2', [
				'e' => $element,
				'group' => $grp
			])
			<div id="group_{{ $grp++ }}" class="__hide row" style="display: none;">
				@php
					$openGroup = true;
				@endphp
				@endif

				@if($element['type'] == 'text')
					@if($element['key'] == 'pais_de_fabricacion')
						@include('admin.formElements.select_country', [
							'e' => $element,
						])
					@else
						@include('admin.formElements.input', [
							'e' => $element,
						])
					@endif
				@endif

				@if($element['type'] == 'number')
					@include('admin.formElements.number', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'boolean')
					@include('admin.formElements.boolean', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'multiline')
					@include('admin.formElements.text', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'select')
					@include('admin.formElements.select', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'multiselect')
					@include('admin.formElements.multiselect', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'percent10')
					@include('admin.formElements.percent10', [
						'e' => $element,
					])
				@endif

				@if($element['type'] == 'range_year')
					@include('admin.formElements.rangeYear', [
						'e' => $element,
					])
				@endif
				@endforeach

resources/views/admin/pages/producto/translation.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@section('css')
@stop

@section('content')

	<ol class="breadcrumb pull-right">
		<li><a href="javascript:;">Home</a></li>
		<li><a href="/admin">Admin</a></li>
		<li class="{{ route('admin.anuncio.index') }}">Traduccion</li>
	</ol>

	<h1 class="page-header">Traducción</h1>

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				{{--<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>--}}
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Traduccion</h4>
		</div>
		<div class="panel panel-body">
			<form id="formTranslation" method="get" class="form-horizontal">
				<table class="table table-condensed table-striped">
					<tr>
						<th class="text-center">Texto Original</th>
						<th class="text-center">Español</th>
						<th class="text-center">Sueco</th>
						<th class="text-center">Inglés</th>
					</tr>
					<tr>
						<td class="text-center" style="vertical-align:middle;">@lang('form.'.$key)</td>
						<td style="vertical-align:middle;">
							{!! Form::text('espaniol', $espaniol, ['id' => 'espaniol', 'class' => 'form-control']) !!}
						</td>
						<td style="vertical-align:middle;">
							{!! Form::text('sueco', $sueco, ['id' => 'sueco', 'class' => 'form-control']) !!}
						</td>
						<td style="vertical-align:middle;">
							{!! Form::text('ingles', $ingles, ['id' => 'ingles', 'class' => 'form-control']) !!}
						</td>
					</tr>
				</table>
				<div class="hr-line-dashed"></div>
				<div class="form-group row">
					<div class="col-lg-12 text-right">
						<a class="btn btn-white btn-sm" data-dismiss="modal" href="javascript:;" onclick="translationCancel()">Cerrar</a>
						<a class="btn btn-primary btn-sm" href="javascript:;" onclick="translationSave()" >Guardar</a>
					</div>
				</div>
			</form>
		</div>
	</div>

@stop

@section('libraries')
@stop

@push('scripts')
	<script>

		$( "#formTranslation" ).submit(function( event ) {
			translationSave();
			event.preventDefault();
		});

		function translationSave(){
			var url = '{{ route('admin.producto.translation', [ $prodId, $key ]) }}';
			ajaxPost(url, {
				es: $('#espaniol').val(),
				se: $('#sueco').val(),
				en: $('#ingles').val()
			}, function(){
				$(document).trigger('formTranslation:aceptar');
			});
		}

		function translationCancel(){
			$(document).trigger('formTranslation:cancelar');
		}

		function formInit(){
		}

	</script>
@endpush

resources/views/admin/pages/producto/translationML.blade.php
@extends(($isAjaxRequest == true) ? 'admin.layouts.ajax' : 'admin.layouts.default')

@section('css')
@stop

@section('content')

	<ol class="breadcrumb pull-right">
		<li><a href="javascript:;">Home</a></li>
		<li><a href="/admin">Admin</a></li>
		<li class="{{ route('admin.anuncio.index') }}">Traduccion</li>
	</ol>

	<h1 class="page-header">Traducción</h1>

	<div class="panel panel-inverse">
		<div class="panel-heading">
			<div class="panel-heading-btn">
				{{--<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>--}}
				<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
			</div>
			<h4 class="panel-title">Traduccion</h4>
		</div>
		<div class="panel panel-body">
			<form id="formTranslation" method="get" class="form-horizontal">
				<table class="table table-condensed table-striped">
					<tr>
						<th class="text-center">Texto Original</th>
						<th class="text-center">Español</th>
						<th class="text-center">Sueco</th>
						<th class="text-center">Inglés</th>
					</tr>
					<tr>
						<td class="text-center" style="vertical-align:middle;">@lang('form.'.$key)</td>
						<td style="vertical-align:middle;">
							{!! Form::textarea('espaniol', $espaniol, ['id' => 'espaniol', 'class' => 'form-control']) !!}
						</td>
						<td style="vertical-align:middle;">
							{!! Form::textarea('sueco', $sueco, ['id' => 'sueco', 'class' => 'form-control']) !!}
						</td>
						<td style="vertical-align:middle;">
							{!! Form::textarea('ingles', $ingles, ['id' => 'ingles', 'class' => 'form-control']) !!}
						</td>
					</tr>
				</table>
				<div class="hr-line-dashed"></div>
				<div class="form-group row">
					<div class="col-lg-12 text-right">
						<a class="btn btn-white btn-sm" data-dismiss="modal" href="javascript:;" onclick="translationCancel()">Cerrar</a>
						<a class="btn btn-primary btn-sm" href="javascript:;" onclick="translationSave()" >Guardar</a>
					</div>
				</div>
			</form>
		</div>
	</div>

@stop

@section('libraries')
@stop

@push('scripts')
	<script>

		$( "#formTranslation" ).submit(function( event ) {
			translationSave();
			event.preventDefault();
		});

		function translationSave(){
			var url = '{{ route('admin.producto.translation', [ $prodId, $key ]) }}';
			ajaxPost(url, {
				es: $('#espaniol').val(),
				se: $('#sueco').val(),
				en: $('#ingles').val()
			}, function(){
				$(document).trigger('formTranslation:aceptar');
			});
		}

		function translationCancel(){
			$(document).trigger('formTranslation:cancelar');
		}

		function formInit(){
		}

	</script>
@endpush